# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Banxx's Blog
avatar: 'https://bcdn.banxx.cn/head.png'
favicon: 'https://bcdn.banxx.cn/head.png'
subtitle: ''
description: ''
keywords:
author: Banxx
language:
  - zh-CN
  - en
  - zh-TW
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://blog.banxx.cn
permalink: :abbrlink/
abbrlink:
  alg: crc32 #算法： crc16(default) and crc32
  rep: hex #进制： dec(default) and hex
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: prismjs

highlight:
  enable: false
  line_number: false
  auto_detect: false
  tab_replace: '    '
  wrap: false
  hljs: true

prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''
  line_threshold: 0

# prism_plugin:
#   mode: 'realtime'    # realtime/preprocess
#   theme: 'default'
#   line_number: true    # default false
#   custom_css: 'prism/prism.css'     # optional
#   prism: coy

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: stellar

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repository: ban@110.40.158.229:/home/git/blog.git   #用户名@服务器Ip:git仓库位置
  branch: master

inject:
  head:
    - <link rel="stylesheet" href="/js/prism/prism.css">
    - <script src="/js/prism/prism.js" async></script>
    - <link rel="stylesheet" href="/css/dark/dark.css"> # 黑夜样式
    - <script type="text/javascript" src="/css/dark/dark_light.js"></script>
    # - <link rel="stylesheet" href="https://gcore.jsdelivr.net/gh/highlightjs/cdn-release@11.5.0/build/styles/atom-one-dark.min.css">
  script:
    - <script type="text/javascript" src="/css/dark/dark.js"></script> # 黑夜控制

# hexo-neat 优化提速插件（去掉HTML、css、js的blank字符）
neat_enable: true
neat_html:
  enable: true
  exclude:
    - '**/*.md'
neat_css:
  enable: true
  exclude:
    - '**/*.min.css'
neat_js:
  enable: true
  mangle: true
  output:
  compress:
  exclude:
    - '**/*.min.js'

Plugins:
- hexo-generator-sitemap

sitemap:
    path: sitemap.xml
